# Generated by Django 3.2.2 on 2021-05-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_items', models.CharField(max_length=30)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
    ]
